# .github/workflows/snake.yml
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GudisaSandeep
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Snake Animation'
          add: 'dist'

# .github/workflows/profile-3d.yml
name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: GudisaSandeep
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D Contribution Graph"
          git push

# .github/workflows/blog-post-workflow.yml
name: Latest Blog Posts
on:
  schedule:
    - cron: '0 */24 * * *' # Runs once a day
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://yourblog.com/feed" # Replace with your blog's RSS feed URL
          max_post_count: 3
          gh_token: ${{ secrets.GITHUB_TOKEN }}

# .github/workflows/profile-views-counter.yml
name: Profile Views Counter
on:
  schedule:
    - cron: '0 */24 * * *' # Runs every 24 hours
  workflow_dispatch:

jobs:
  views-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GudisaSandeep/views-counter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# .github/workflows/update-stats.yml
name: Update GitHub Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: GudisaSandeep
